### PR TITLE
add class_methods support

### PR DESCRIPTION
**Pull request by barelyknown**
`ClassMethods` from `ActiveSupport::Concern` was not supported in a way that felt natural, so I added `class_methods`.

### CODE REVIEW

**Comment by barelyknown** [comment]
Any chance you can merge this in?

**Comment by jeremy** [comment]
@barelyknown Nice! Could you submit a similar PR to Rails (since `Module#concerning` will be included in Rails 4.1+) as well?

**Comment by johnnaegle** [comment]
Thanks!

**Comment by barelyknown** [comment]
Oh, I thought that it was included in Rails 4.1+ via a gem? Is it just directly integrated?

**Pull request merged**
